### ISSUE TITLE
top mount smg STILL jams

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1337] opened 2023-10-14 04:11 UTC
### Description of issue

unless its something with the server updating, the SMG still jams when using lethal ammo
![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/00aa00e0-01cd-49d2-8a33-2842607607e8)

### Steps to reproduce

load top mount smg with ...ammo_magazine/smg_top and start shooting till it jams

### Client version, server revision, & game ID

Client Version: 514
Server Revision: 3a733b20e8ec271813106ceb08db5d359df047ad - 13106ceb08db5d359df047ad - 2023-10-13
Game ID: cqh-aAYt

### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by CPU-Blanc** [comment] 2023-10-14 12:26
Duplicate of #1310. Please re-open/comment on existing issues in future

**Closed by CPU-Blanc** 2023-10-14 12:26 UTC
Labels: Bug, Needs Triage
