### ISSUE TITLE
Old blueshield body armor has no armor

### ISSUE THREAD

**Issue by CaraS212** [UristMcStation/UristMcStation#1300] opened 2023-10-07 02:52 UTC
### Description of issue

![image](https://github.com/UristMcStation/UristMcStation/assets/107084118/4b6d9798-d79d-412d-a6e6-4e1807c6be12)

### Steps to reproduce

open view var

### Client version, server revision, & game ID

latest as of date of posting

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by ggermanicus** [comment] 2023-10-07 03:26
It's a plate carrier. I'll code in something to make it more obvious soontm

**Comment by CPU-Blanc** [comment] 2023-10-07 12:17
Yeah, it's a plate carrier so shouldn't have any armour with no plates loaded. Working as intended however as grant said, could be made more obvious

**Comment by CPU-Blanc** [comment] 2023-10-08 12:09
Addressed in #1309

**Closed by CPU-Blanc** 2023-10-08 12:09 UTC
Labels: Oversight, Priority: Low
