### ISSUE TITLE
Clown & Mime lost maintenance access

### ISSUE THREAD

**Issue by Yantarii** [UristMcStation/UristMcStation#1395] opened 2023-12-23 17:03 UTC
### Description of issue

Clown & Mime no longer have maintenance access.
They are now tool storage's strongest test wire soldiers.

### Difference between expected and actual behaviour

Clown & Mime had maintenance access before, I'm not sure when but at some point it disappeared.
Maybe they are still defined somewhere as assistants, or a sub-title, etc.

Expected:
Clown and Mime have maintenance access again

### Steps to reproduce

1. Spawn as Clown or Mime
2. Walk to a maintenance door
3. Honk sadly.

### Specific information for locating

Clown & Mime job types in nerva jobs datum, or some sort of access thing.

### Client version, server revision, & game ID

Current Revision - Baymerge Testing Version.

### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)

**Comment by ggermanicus** [comment] 2023-12-26 10:41
Looks intentional and recent on Glloyd's part: https://github.com/UristMcStation/UristMcStation/pull/1370

**Comment by Yantarii** [comment] 2023-12-28 03:08
seems like it yep, damn fair enough

**Comment by CPU-Blanc** [comment] 2024-02-23 20:45
Gonna close this as it seems intentional and there's been no further input.
We can re-open this if that later turns out to be a regression.

**Closed by CPU-Blanc** 2024-02-23 20:45 UTC
Labels: Bug, Priority: Medium

**Comment by Glloyd** [comment] 2024-02-23 23:26
Intentional yeah, they have the same access to maint as assistants do - through their workplace and through the false wall in the abandoned room across the hall from their spawn.
