### ISSUE TITLE
Supermatter chamber melts at high heat

### ISSUE THREAD

**Issue by liction15** [UristMcStation/UristMcStation#426] opened 2016-04-10 06:17 UTC
I know melting walls are intended but do you think we could make the rwalls around the supermatter core like the ones around the toxins burn chamber? The walls are fairly easy to melt and sometimes take damage during normal use. 

It has melted twice just today, although in less then ideal circumstances, first was when the core got exposed to oxygen and overheated after melting the core walls. The second time was when I was trying to run a hybrid oldschool thermal engine and supermatter setup by burning phoron and oxygen to reach useful temperature faster and the supermatter to maintain it, the core only overheated after melting through the wall I then quickly patched and the engine ran with no problems for the rest of the round.

**Comment by Addle** [comment] 2016-04-10 07:01
Sounds like normal engine maintenance to me.

**Comment by Vakothu** [comment] 2016-04-10 10:25
Even the toxins burn chamber melts at 6000K now, it's because of the material overhaul.  To increase the temp. resistance of the walls, we'd need to change the melting point of plasteel, which would be all plasteel.  Or make a new material, that people would promptly scavenge from those walls as you can't get it elsewhere.

**Comment by liction15** [comment] 2016-04-10 11:34
I thought it was possible to change the temperature resistance of rwalls in the map or is that no longer the case?

**Comment by scrdest** [comment] 2016-04-10 13:47
I believe that phoronglass is a highly heat-resistant material intended for the engine.

**Comment by Glloyd** [comment] 2016-04-11 06:49
yeah, the melting point is determined by the material. i'll look mor into
how its handled and see if I can add a check for certain types of walls, or
else add an extra reinforced wall that doubles the heat resistance or
somesuch.

On Sun, Apr 10, 2016 at 9:47 AM, scrdest <notifications@github.com> wrote:

> I believe that phoronglass is a highly heat-resistant material intended
> for the engine.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UristMcStation/UristMcStation/issues/426#issuecomment-207987842>
>



-- 
Graham Lloyd

**Comment by Glloyd** [comment] 2016-04-12 05:25
#bringbacktheFuckingBaylabel2016

**Comment by scrdest** [comment] 2016-04-12 10:29
Seriously, just make it all (reinforced) phoronglass.

**Comment by Glloyd** [comment] 2016-04-12 22:30
the question is whether this is something that should be addressed, as there should be a little bit of danger to the process.

**Comment by Vakothu** [comment] 2016-04-13 19:30
If you get above 5000 Kelvin, the SM is getting damaged by the ambient heat anyways, so you never really should intentionally get the temperature to the 6000 Kelvin melting point.

**Comment by Glloyd** [comment] 2016-04-13 20:33
In that case, it's not really an issue, and more part of the careful balancing act that can be engineering.

**Comment by Glloyd** [comment] 2016-04-19 09:25
Closing this for now. As it is, it's working as intended. I was burning an incredibly hot mix in toxins the other day and I didn't have any issues with it burning through the floor. In normal gameplay if the proper precautions are taken, this isn't an issue.

**Closed by Glloyd** 2016-04-19 09:25 UTC
Labels: Balance, Map
